### ISSUE TITLE
Chart 10.1.0: statefull-set rendering issue

### ISSUE THREAD

**Issue by fuson** [ibm-messaging/mq-helm#102]
Helm chart value file:

-------------
```yaml
license: "accept"

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

# queueManager section specifies settings for the MQ Queue Manager
queueManager:
  # name allows you to specify the name to use for the queue manager.  Defaults to the Helm release name.
  name: PCMQ
  # Environment variables to be associated with the queue manager containers
  envVariables:
    - name: LICENSE
      value: accept
    - name: MQ_QMGR_NAME
      value: PCMQ
    - name: MQ_APP_PASSWORD
      value: "app"
    - name: MQ_ADMIN_PASSWORD
      value: "admin"

web:
  enable: true
  manualConfig:
    configMap:
      name: web-config
```
-------------

in helm template --debug mode i see this one (beginning part):

-------------
```text
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ibm-mq
  labels:
    helm.sh/chart: ibm-mq-10.1.0
    app.kubernetes.io/name: ibm-mq
    app.kubernetes.io/instance: ibm-mq
    app.kubernetes.io/version: "9.4.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-mq
      app.kubernetes.io/instance: ibm-mq
  serviceName: qm
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        helm.sh/chart: ibm-mq-10.1.0
        app.kubernetes.io/name: ibm-mq
        app.kubernetes.io/instance: ibm-mq
        app.kubernetes.io/version: "9.4.0.0"
        app.kubernetes.io/managed-by: Helm
        statefulSetName: ibm-mq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - "amd64"
                - "s390x"
                - "ppc64le"
              - key: kubernetes.io/os
                operator: In
                values:
                - "linux"
      serviceAccountName: ibm-mq
      securityContext:
        fsGroup: 
        supplementalGroups:
      - name: cm-webxml-web-config
        configMap:
          name: web-config
          defaultMode: 0644
          items:
            - key: mqwebuser.xml
              path: mqwebuser.xml
      terminationGracePeriodSeconds: 30
      containers:
        - name: qmgr
          image: "icr.io/ibm-messaging/mq:9.4.0.0-r3"
          imagePullPolicy: IfNotPresent
          terminationMessagePath: "/run/termination-log"
          ports:
          - containerPort: 1414
          - containerPort: 9443
          - containerPort: 9157
          env:
          - name: LICENSE
            value: accept
          - name: MQ_QMGR_NAME
            value: "PCMQ"
          - name: MQ_NATIVE_HA
            value: "false"
          - name: MQ_ENABLE_EMBEDDED_WEB_SERVER
            value: "true"
          - name: MQ_LOGGING_CONSOLE_FORMAT
            value: basic
          - name: MQ_ENABLE_METRICS
            value: "true"
          - name: DEBUG
            value: "false"
          - name: MQ_ENABLE_TRACE_STRMQM
            value: "false"
          - name: MQ_ENABLE_TRACE_CRTMQDIR
            value: "false"
          - name: MQ_ENABLE_TRACE_CRTMQM
            value: "false"
          - name: MQ_EPHEMERAL_PREFIX
            value: "/run/mqm"
          - name: MQ_GRACE_PERIOD
            value: "29"
          - name: LICENSE
            value: "accept"
          - name: MQ_QMGR_NAME
            value: "PCMQ"
          - name: MQ_APP_PASSWORD
            value: "app"
          - name: MQ_ADMIN_PASSWORD
            value: "admin"
          volumeMounts:
          - mountPath: "/mnt/mqm"
            name: qm
          - name: cm-webxml-web-config
            mountPath: "/etc/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml"
            subPath: "mqwebuser.xml"
            readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop:
                - ALL
          # Set liveness probe to determine if the queue manager is running
          livenessProbe:
            exec:
              command:
              - chkmqhealthy
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Set readiness probe to determine if the MQ listener is running
          readinessProbe:
            exec:
              command:
              - chkmqready
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 1
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: qm
      labels:
        app.kubernetes.io/name: ibm-mq
        app.kubernetes.io/instance: ibm-mq
        app.kubernetes.io/managed-by: Helm
    spec:
      # If present, use the storageClassName from the values.yaml, else use the
      # default storageClass setup by Kubernetes Administrator
      #
      # Setting storageClassName to nil means use the default storage class
      storageClassName: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "2Gi"
```
-------------

And as a result:

Error: YAML parse error on ibm-mq/templates/stateful-set.yaml: error converting YAML to JSON: yaml: line 66: did not find expected key
