### ISSUE TITLE
is it possible to provide trust store public keys via ConfigMap?

### ISSUE THREAD

**Issue by WalkerWalker** [ibm-messaging/mq-helm#57]
After reading the readme, I found that it is only possible to provide trust store public keys via Secret

```
pki:
  trust:
    - name: default
      secret:
        secretName: appsecret
        items:
          - app.crt
```

Would it be possible to support providing trust via config map?  In our ocp cluster, the service ca is provided as a config map.
