### ISSUE TITLE
Adding a Custom Shell Script in a Kubernetes Job

### ISSUE THREAD

**Issue by uaw013** [ibm-messaging/mq-helm#86]
I've been trying to add a custom shell script using a Kubernetes job, but it doesn't seem to be working. The YAML file for the job is included below.

It appears that the problem might be related to the state of the replica pods. They are in the "running" state but not in the "ready" state. This is how the system is designed. You can refer to the IBM community discussion for more details: IBM MQ NativeHA on Kubernetes with IBM Messaging/MQ Helm Chart.

What is the best practice to do this? 

Here is the YAML file I'm using:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ibm-mq-tst
    helm.sh/chart: ibm-mq-8.0.0 
  name: install-scripts
  namespace: mq-tst
spec:
  template:
    metadata:
      name: install-scripts
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: ibm-mq-tst
        helm.sh/chart: ibm-mq-8.0.0 
    spec:
      restartPolicy: Never
      containers:
      - name: install-script
        image: "icr.io/ibm-messaging/mq:9.3.5.0-r2"
        command: ["/bin/sh", "-c", "chmod +x /etc/mqm/setAppSecurity.sh", "/etc/mqm/setAppSecurity.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true 
```
